server:
  port: 8080

spring:
  application:
    name: zuul-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  prefix: "/meetingfilm/"
  routes:
    meetingfilm-user:
      path: /userapi/**
      serviceId: user-service
      retryable: true

logging:
  config: classpath:logback.xml