server:
  port: 8301


management:
  endpoints:
    web:
      exposure:
        include: "*"

mybatis-plus:
  mapper-locations: classpath*:com/mooc/jiangzh/**/xml/*Mapper.xml
  global-config:
    id-type: 0
    db-column-underline: false
    refresh-mapper: true

spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true
  application:
    name: cinema-service
  datasource:
    url: jdbc:mysql://mysql-cn-north-1-91280540eb0a4ed6.public.jcloud.com:3306/iot_moc?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: jiangzh
    password: Jiangzh_001
    filters: log4j,wall,mergeStat

logging:
  config: classpath:logback.xml
